// ADD
const ADD_SERVICE_STARTED = "ADD_SERVICE_STARTED";
const ADD_SERVICE_SUCCESS = "ADD_SERVICE_SUCCESS";
const ADD_SERVICE_FAILURE = "ADD_SERVICE_FAILURE";

// GET
const GET_SERVICES_STARTED = "GET_SERVICES_STARTED";
const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
const GET_SERVICES_FAILURE = "GET_SERVICES_FAILURE";
// EDIT
const EDIT_SERVICE_STARTED = "EDIT_SERVICES_STARTED";
const EDIT_SERVICE_SUCCESS = "EDIT_SERVICES_SUCCESS";
const EDIT_SERVICE_FAILURE = "EDIT_SERVICES_FAILURE";
// DELETE
const DELETE_SERVICE_STARTED = "DELETE_SERVICES_STARTED";
const DELETE_SERVICE_SUCCESS = "DELETE_SERVICES_SUCCESS";
const DELETE_SERVICE_FAILURE = "DELETE_SERVICES_FAILURE";


const GET_DAYINFO_STARTED = "GET_DAYINFO_STARTED";
const GET_DAYINFO_SUCCESS = "GET_DAYINFO_SUCCESS";
const GET_DAYINFO_FAILURE = "GET_DAYINFO_FAILURE";
export {
    ADD_SERVICE_FAILURE, ADD_SERVICE_STARTED, ADD_SERVICE_SUCCESS,
    GET_SERVICES_FAILURE, GET_SERVICES_SUCCESS, GET_SERVICES_STARTED,
    EDIT_SERVICE_FAILURE, EDIT_SERVICE_SUCCESS, EDIT_SERVICE_STARTED,
    DELETE_SERVICE_FAILURE, DELETE_SERVICE_SUCCESS, DELETE_SERVICE_STARTED,
    GET_DAYINFO_FAILURE, GET_DAYINFO_SUCCESS, GET_DAYINFO_STARTED
};